### ISSUE TITLE
EfficientAd pretrained weights access denied

### ISSUE THREAD

**Issue by pankajmishra000** [LeapMind/PUAD#9]
Access to the Pretrained weights of the EfficientAD is denied.

Kindly open source the weights by modifying the access rights in your Google Drive folder containing its weight. I already raised a couple of times for the access but it has not been answered.
![image](https://github.com/LeapMind/PUAD/assets/36365254/591c0954-86b8-4d12-a43f-df77e68cf150)

**Comment by ry-immr** [comment]
Thank you for letting us know about the access issue with the pre-trained model files. We've now updated the link in README.md to a new one that doesn't require any access rights, so it should be accessible to everyone.

Could you please try the updated link and confirm that it works? We appreciate your patience and your report!

**Comment by pankajmishra000** [comment]
The new link works fine. Thanks for the update.
